GoogleCloudPlatform/functions-framework-conformance

- client/validate.go
Since Go doesn't fallthrough on switch cases.
> Remove shorthands and use full event names

- legacy_event_data/firebase-auth1.json
- legacy_event_data/firebase-auth2.json
- legacy_event_data/firebase-db1.json
- legacy_event_data/firebase-db2.json
- legacy_event_data/firebase-db3.json
- legacy_event_data/firebase-db4.json
- legacy_event_data/firebase-db5.json
- legacy_event_data/firebase-db6.json
- legacy_event_data/firebase-db7.json
- legacy_event_data/firebase-db8.json
- legacy_event_data/firebase-dbdelete1.json
- legacy_event_data/firebase-dbdelete2.json
- legacy_event_data/firestore_complex.json
- legacy_event_data/firestore_simple.json
- legacy_event_data/legacy_pubsub.json
- legacy_event_data/legacy_storage_change.json
- legacy_event_data/pubsub_binary.json
- legacy_event_data/pubsub_text.json
- legacy_event_data/storage.json
Adds the source of truth legacy event data to the FF conformance repo.
We currently have test data in our individual FFs. Eventually we want to ensure that we can accept these payloads in conformance tests.
- https://github.com/GoogleCloudPlatform/functions-framework-dotnet/tree/master/src/Google.Cloud.Functions.Framework.Tests/GcfEvents
- https://github.com/GoogleCloudPlatform/functions-framework-ruby/tree/master/test/legacy_events_data
> feat: add legacy event json files

- events/validators.go
- go.mod
- go.sum
Rather than just using a string output, validate cloud events by field. Allows for more fine-grained control if we need to do additional validation on the different fields.
> Field-wise validation for CloudEvents

- README.md
- client/main.go
- client/start.go
- client/validate.go
When the flag `-run-in-container` (false by default) is set to true, we run the functions framework in a container. The function output file will be copied to the local file system for the validation. This can be used to validate container images built by our buildpacks. For example, to validate a function image called `fn-image`, run
```
./client -cmd="fn-image" -type="http" -run-in-container="true"
```
> feat: support validation of container images

- client/validate.go
- events/events.go
- events/validators.go
- events/validators_test.go
Collect errors and report as a whole, rather than bailing on the first
error. Also report which events have been tested and why any were
skipped.
> Improve error reporting

- events/validators.go
When a legacy event is converted to a CloudEvent, we know that we want a certain
JSON payload, but we shouldn't require that payload to be formatted exactly the
same as the JSON payload in our golden files. Instead, we unmarshal both the
actual and expected values into maps, and we check that those maps are equal.
> Loosen requirements on the data payload of CloudEvents.

- action/src/index.ts
When using the action in other functions frameworks' CI workflows, the comformance tool is not local so `go install` would fail with the error
```
can't load package: package github.com/GoogleCloudPlatform/functions-framework-conformance/client: cannot find package "github.com/GoogleCloudPlatform/functions-framework-conformance/client" in any of:
/opt/hostedtoolcache/go/1.13.15/x64/src/github.com/GoogleCloudPlatform/functions-framework-conformance/client (from $GOROOT)
/home/runner/go/src/github.com/GoogleCloudPlatform/functions-framework-conformance/client (from $GOPATH)
```
Using `go get` will both download and install the conformance tool.
> fix: run `go get` in conformance action

- events/events_data.go
- events/generate/data/firebase-db3-legacy-input.json
- events/generate/data/firebase-dbdelete2-legacy-input.json
- events/generate/data/firebase-dbdelete2-legacy-output.json
There were source/resource mismatches in the firebase-db3 and
firebase-dbdelete2 test cases. Tests that convert between legacy events
and CloudEvents fail because the input and output source/resource
didn't match.
> Fix mismatch between legacy events and CloudEvents in two test cases

- client/validate.go
- events/validators.go
- events/validators_test.go
As issue #54, this allow modifying the CloudEvent "input" files without breaking the "CloudEvents to CloudEvents" tests.
> fix: use input data as the expected values for "CloudEvents to CloudEvents" tests

- client/local.go
Child processes of the command weren't killed. Make a process group
and then kill the group instead of just killing the command.
> fix: properly kill child processes

- events/events.go
- events/events_data.go
- events/generate/data/README.md
- events/generate/data/legacy_pubsub-legacy-output-converted.json
- events/generate/events_generate.go
- events/validators.go
- events/validators_test.go
There are multiple legacy Pub/Sub payload schemas. For example, see:
- `legacy_pubsub-legacy-output.json`
- `pubsub_text-legacy-output.json`
When converting Cloud Events to legacy events there is no information
in the CE that enables us to infer which schema to use for the conversion.
Unfortunately, this tool assumes the converted output will always match
a corresponding unconverted payload, which isn't necessarily possible.
This commit adds a mechanism to override the expected output when
converting between event types and creates an override for converting
the `legacy_pubsub` test case.
> Override the expected converted Pub/Sub payload

- README.md
Golang flag library does not allow boolean flags to be specified with a
space (https://pkg.go.dev/flag#hdr-Command_line_flag_syntax).
> docs: Fix example commands for running client

- client/concurrency.go
- client/main.go
- client/validate.go
1. Example output:
```
FUNCTION_TARGET=concurrentCloudEvent client -buildpacks=false -type=cloudevent -cmd='go run testdata/conformance/cmd/declarative/main.go' -start-delay 5 -validate-concurrency=true
2022/01/20 10:52:28 Validating for cloudevent...
2022/01/20 10:52:28 Framework server started.
2022/01/20 10:52:33 cloudevent validation with concurrent requests...
2022/01/20 10:52:34 Single request response time benchmarked, took 1.003920604s for 1 request
2022/01/20 10:52:34 Starting 10 concurrent workers to send requests
2022/01/20 10:52:35 Worker #4 done
2022/01/20 10:52:35 Worker #2 done
2022/01/20 10:52:35 Worker #6 done
2022/01/20 10:52:35 Worker #1 done
2022/01/20 10:52:35 Worker #5 done
2022/01/20 10:52:35 Worker #9 done
2022/01/20 10:52:35 Worker #8 done
2022/01/20 10:52:35 …
```
> feature: add ability to test concurrent requests

- .github/actions/client/install/action.yml
This decomposes the existing conformance test action into two steps:
download and run
This allows:
- caching of the client within a Workflow and between Workflow runs
- setup-go action to be skipped since it is now part of "download"
- removal of TypeScript action because the "run" logic is now trivial
Calling GitHub Workflows can now trivially run the client in one line
with the normal flags (e.g. 'client -buildpacks=false -type=http
-cmd='go run testdata/conformance/cmd/http/main.go' -start-delay 5
-validate-mapping=true') instead of calling a GitHub action with unique
syntax for input flags that are disjoint from running locally.
> feat: Add new GitHub Action for installing client

- .github/workflows/buildpack-integration-test.yml
This can be used by Functions Frameworks to test the framework against
the official GCF builders, ensuring the frameworks will work containerized.
It runs HTTP tests similar to the local conformance test client runs, except in buildpack mode which:
1. Builds the function into a container using `pack` and the appropriate GCF builder
2. Runs the container on docker
3. Sends standard conformance test HTTP requests to the running container and verifies the response
Optimizations:
- Conformance test client is cached by client version, so it doesn't have to be rebuilt/re-installed unless there's a new release
- Each conformance test client run is run in its own GitHub job/runner in parallel
Example `.github/workflows/buildpack-integration-test.yml` that would go in an FF repo:
```yaml
name: …
```
> feat: Add reusable Workflow for buildpack integration test

- .github/workflows/buildpack-integration-test.yml
This gives the various FF repos the chance to execute bash commands to
setup the test function to use the GitHub commit under test  before running the buildpack test.
Example config for FF Go repo:
```yaml
go113-buildpack-test:
uses: GoogleCloudPlatofrm/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@v1.4.0
with:
http-builder-source: 'testdata/conformance/function'
http-builder-target: 'declarativeHTTP'
cloudevent-builder-source: 'testdata/conformance/function'
cloudevent-builder-target: 'declarativeCloudEvent'
prerun: 'testdata/conformance/function/prerun.sh ${{ github.sha }}' # prerun.sh uses the github.sha to modify go.mod file
builder-runtime: 'go113'
builder-tag: 'go113_20220320_1_13_15_RC00'
```
> feat: add prerun hook to buildpack integration test

- client/buildpacks.go
This is important to ensure that the builds work.
> fix: add GCF as a target platform when testing with GCF buildpacks

- client/buildpacks.go
Use the 'gcr.io' bucket for finding builders, which are tagged with the
'latest' tag.
Also, turn on verbose logging for the `pack` build step to help with
debugging.
> feat: support latest builder tag

- client/buildpacks.go
Look for the output file in the correct location. Also use a temp
for the where the file gets copied to prevent spamming local filesystem.
> fix: respect -output-file flag in buildpacks mode

- .github/workflows/buildpack-integration-test.yml
Match the default value used by the conformance test client. The flag is
always passed through by the buildpack integration test workflow, so
this ensures it's not empty string by default.
> fix: add default output-file workflow value

- client/concurrency.go
Raises the bar for passing concurency to handling 1000 requests
simultaneously that must finish within 2*(time for one request).
> feature: test 1000 concurrent requests at a time

- client/buildpacks.go
- client/local.go
- client/main.go
- client/validate.go
Add a parameter for consuming runtime variable (-envs)
Sample command- client -buildpacks=true -type=http -builder-target=write_http_declarative_concurrent -builder-source tests/conformance -start-delay 1 -validate-concurrency=true -builder-runtime=python310 -builder-tag=python310_20220320_3_10_2_RC00 -envs web_concurrency_workers=4,web_concurrency_threads=3
> feat: Add a parameter to consume additional runtime variables for docker run

- client/concurrency.go
This reverts commit 4f37e559575e4770aad085cde8ac0b65b85e9036.
Setting the number of requests for concurrency tests back to 10.
> Revert "feature: test 1000 concurrent requests at a time (#112)"

- .github/actions/client/install/action.yml
- .github/workflows/buildpack-integration-test.yml
This makes the action more flexible so Action users can define their own destination path instead of needing to know that it will be installed at `~/go/bin/client`
> feat: add 'cache-path' parameter to actions/client/install

- .github/workflows/main.yml
- client/buildpacks.go
This includes the ability to use the latest tag to always test with the latest builder.
> feat: use gae-runtimes GCR for builders

- .github/workflows/buildpack-integration-test.yml
- client/buildpacks.go
- client/start.go
Improves debugability of buildpack integration tests by capturing logs from inside the containers that run under this test and uploading those logs as test artifacts.
> chore: buildpack integ tests upload logs from container

- client/buildpacks.go
- client/buildpacks_test.go
Use unified language specific builders to make tests as close as possible to prod deployments.
> fix: use gcf runtime specific builder instead of unified builder

- go.mod
This should fix the "Invalid Go toolchain version" message in the Security page
> chore: Update go.mod to use 1.21.13

- .github/workflows/buildpack-integration-test.yml
Add ${{ inputs.builder-runtime }} to the `name` for artifact upload. This will avoid the conflict in names, where e.g. php81, php82 and php83 will try to upload the artifacts with the same name and the second and later attempts will fail:
```
Run actions/upload-artifact@v4
with:
name: cloudevent_buildpack_integ_logs
path: /tmp/ff_*
retention-days: 5
if-no-files-found: warn
compression-level: 6
overwrite: false
include-hidden-files: false
With the provided path, there will be 2 files uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
https://github.com/GoogleCloudPlatform/functions-framework-php/actions/runs/13191006742 …
> fix: Update buildpack-integration-test.yml
